### ISSUE TITLE
pip install fails on C compilation

### ISSUE THREAD

**Issue by alex-kowalczyk** [jmackie4/rouleur#1]
Ubuntu 17.04, pip 9.0.1, python 2.7 venv
Any suggestions how to fix C compilation errors?

Collecting rouleur
  Using cached rouleur-0.0.3.tar.gz
Requirement already satisfied: numpy>=1.11.1 in /home/alex/Documents/src/venv/strava/lib/python2.7/site-packages (from rouleur)
Requirement already satisfied: scipy>=0.18.1 in /home/alex/Documents/src/venv/strava/lib/python2.7/site-packages (from rouleur)
Building wheels for collected packages: rouleur
  Running setup.py bdist_wheel for rouleur ... error
  Complete output from command /home/alex/Documents/src/venv/strava/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5JwT6r/rouleur/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpXHfBPWpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/rouleur
  copying rouleur/_util.py -> build/lib.linux-x86_64-2.7/rouleur
  copying rouleur/_modelling.py -> build/lib.linux-x86_64-2.7/rouleur
  copying rouleur/pyeqn.py -> build/lib.linux-x86_64-2.7/rouleur
  copying rouleur/__init__.py -> build/lib.linux-x86_64-2.7/rouleur
  copying rouleur/_exceptions.py -> build/lib.linux-x86_64-2.7/rouleur
  running build_ext
  building 'rouleur.ceqn' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/rouleur
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c rouleur/ceqn.c -o build/temp.linux-x86_64-2.7/rouleur/ceqn.o
  rouleur/ceqn.c:153:15: error: variable ‘rouleurmodule’ has initializer but incomplete type
   static struct PyModuleDef rouleurmodule = {
                 ^~~~~~~~~~~
  rouleur/ceqn.c:154:4: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function)
      PyModuleDef_HEAD_INIT,
      ^~~~~~~~~~~~~~~~~~~~~
  rouleur/ceqn.c:154:4: warning: excess elements in struct initializer
  rouleur/ceqn.c:154:4: note: (near initialization for ‘rouleurmodule’)
  rouleur/ceqn.c:155:4: warning: excess elements in struct initializer
      "ceqn",          // name of the module (used in setup.py)
      ^~~~~~
  rouleur/ceqn.c:155:4: note: (near initialization for ‘rouleurmodule’)
  rouleur/ceqn.c:156:4: warning: excess elements in struct initializer
      NULL,            // doc string, may be NULL
      ^~~~
  rouleur/ceqn.c:156:4: note: (near initialization for ‘rouleurmodule’)
  rouleur/ceqn.c:157:4: warning: excess elements in struct initializer
      -1,              // -1 if the module keeps state in global variables
      ^
  rouleur/ceqn.c:157:4: note: (near initialization for ‘rouleurmodule’)
  rouleur/ceqn.c:158:4: warning: excess elements in struct initializer
      RouleurMethods
      ^~~~~~~~~~~~~~
  rouleur/ceqn.c:158:4: note: (near initialization for ‘rouleurmodule’)
  rouleur/ceqn.c: In function ‘PyInit_ceqn’:
  rouleur/ceqn.c:166:10: warning: implicit declaration of function ‘PyModule_Create’ [-Wimplicit-function-declaration]
     return PyModule_Create(&rouleurmodule);
            ^~~~~~~~~~~~~~~
  rouleur/ceqn.c:166:10: warning: ‘return’ with a value, in function returning void
     return PyModule_Create(&rouleurmodule);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  rouleur/ceqn.c:164:1: note: declared here
   PyInit_ceqn(void)    // name is important!
   ^~~~~~~~~~~
  rouleur/ceqn.c: At top level:
  rouleur/ceqn.c:153:27: error: storage size of ‘rouleurmodule’ isn’t known
   static struct PyModuleDef rouleurmodule = {
                             ^~~~~~~~~~~~~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for rouleur
  Running setup.py clean for rouleur
Failed to build rouleur
Installing collected packages: rouleur
  Running setup.py install for rouleur ... error
    Complete output from command /home/alex/Documents/src/venv/strava/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5JwT6r/rouleur/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5WsvJy-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/alex/Documents/src/venv/strava/include/site/python2.7/rouleur:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/rouleur
    copying rouleur/_util.py -> build/lib.linux-x86_64-2.7/rouleur
    copying rouleur/_modelling.py -> build/lib.linux-x86_64-2.7/rouleur
    copying rouleur/pyeqn.py -> build/lib.linux-x86_64-2.7/rouleur
    copying rouleur/__init__.py -> build/lib.linux-x86_64-2.7/rouleur
    copying rouleur/_exceptions.py -> build/lib.linux-x86_64-2.7/rouleur
    running build_ext
    building 'rouleur.ceqn' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/rouleur
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c rouleur/ceqn.c -o build/temp.linux-x86_64-2.7/rouleur/ceqn.o
    rouleur/ceqn.c:153:15: error: variable ‘rouleurmodule’ has initializer but incomplete type
     static struct PyModuleDef rouleurmodule = {
                   ^~~~~~~~~~~
    rouleur/ceqn.c:154:4: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function)
        PyModuleDef_HEAD_INIT,
        ^~~~~~~~~~~~~~~~~~~~~
    rouleur/ceqn.c:154:4: warning: excess elements in struct initializer
    rouleur/ceqn.c:154:4: note: (near initialization for ‘rouleurmodule’)
    rouleur/ceqn.c:155:4: warning: excess elements in struct initializer
        "ceqn",          // name of the module (used in setup.py)
        ^~~~~~
    rouleur/ceqn.c:155:4: note: (near initialization for ‘rouleurmodule’)
    rouleur/ceqn.c:156:4: warning: excess elements in struct initializer
        NULL,            // doc string, may be NULL
        ^~~~
    rouleur/ceqn.c:156:4: note: (near initialization for ‘rouleurmodule’)
    rouleur/ceqn.c:157:4: warning: excess elements in struct initializer
        -1,              // -1 if the module keeps state in global variables
        ^
    rouleur/ceqn.c:157:4: note: (near initialization for ‘rouleurmodule’)
    rouleur/ceqn.c:158:4: warning: excess elements in struct initializer
        RouleurMethods
        ^~~~~~~~~~~~~~
    rouleur/ceqn.c:158:4: note: (near initialization for ‘rouleurmodule’)
    rouleur/ceqn.c: In function ‘PyInit_ceqn’:
    rouleur/ceqn.c:166:10: warning: implicit declaration of function ‘PyModule_Create’ [-Wimplicit-function-declaration]
       return PyModule_Create(&rouleurmodule);
              ^~~~~~~~~~~~~~~
    rouleur/ceqn.c:166:10: warning: ‘return’ with a value, in function returning void
       return PyModule_Create(&rouleurmodule);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    rouleur/ceqn.c:164:1: note: declared here
     PyInit_ceqn(void)    // name is important!
     ^~~~~~~~~~~
    rouleur/ceqn.c: At top level:
    rouleur/ceqn.c:153:27: error: storage size of ‘rouleurmodule’ isn’t known
     static struct PyModuleDef rouleurmodule = {
                               ^~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/alex/Documents/src/venv/strava/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5JwT6r/rouleur/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5WsvJy-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/alex/Documents/src/venv/strava/include/site/python2.7/rouleur" failed with error code 1 in /tmp/pip-build-5JwT6r/rouleur/

**Comment by jmackie** [comment]
Apologies, `setup.cfg` should specify that the package is written for python 3.

**Comment by alex-kowalczyk** [comment]
thanks!
